name: Deploy

on:  
  push:
    branches:
      - main
      - ci/setup
    paths:
      - '.github/workflows/deployment.yml'
      - 'compose.yml'

env:
  export BACKEND_PORT: ${{ vars.BACKEND_PORT }}
  export FRONTEND_PORT: ${{ vars.FRONTEND_PORT }}
  export  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  export exportexport DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
  export DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  export ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
  export REPOSITORY_OWNER: ${{ github.repository_owner }}
  export TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout orchesrator
        uses: actions/checkout@v4

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ vars.FRONTEND_SERVICE_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: ${{ vars.FRONTEND_SERVICE_NAME }}

      - name: Checkout backend
        uses: actions/checkout@v4
        with: 
          repository: ${{ github.repository_owner }}/${{ vars.BACKEND_SERVICE_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: ${{ vars.BACKEND_SERVICE_NAME }}

      - name: Login to GHCR
        uses: docker/login-action@v4
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }} 

      - name: Build and push all to GHCR        
        run: |
          docker compose build
          docker compose push
          
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0  
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.GH_PAT }}" | docker login ghcr.io \
              -u "${{ github.repository_owner }}" \
              --password-stdin

            cd projects/conduit-deployment
            
            docker compose pull
            docker compose up -d --force-recreate