name: Service deployment

on: 
  workflow_call:
    inputs:     
      tag: # The tag of the image to deploy, the git sha is used in this project   
        required: true
        type: string

      service: # The service to deploy, either frontend or backend etc.
        required: true
        type: string

      port: # The port a container to run on. In production this is configured centrally and scoped to repositories.
        required: true
        type: string

      vps-host: # The host of the VPS to deploy to. In production this is configured centrally and scoped to repositories.
        required: true
        type: string

      vps-username: # The username to use when connecting to the VPS. In production this is configured centrally and scoped to repositories.
        type: string

      frontend-service-name: # A servide configured in compiose file. In production this is configured centrally and scoped to repositories.
        type: string

      backend-service-name: # A service configured in compose file. In production this is configured centrally and scoped to repositories.
        type: string 
    
    secrets:
      VPS_SSH_KEY: # The private SSH key to connect to the VPS. In production this is configured centrally and scoped to repositories.
          required: true
     
      GH_PAT:
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ inputs.vps-host }}
          username: ${{ inputs.vps-username }}
          key: ${{ secrets.vps-ssh-key }}
          script: |
            echo "${{ secrets.gh-pat }}" | docker login ghcr.io \
              -u "${{ github.repository_owner }}" \
              --password-stdin

            cd projects/conduit-deployment

            export TAG=${{ inputs.tag }}
            export REPOSITORY_OWNER=${{ github.repository_owner }}
            export  VPS_SSH_KEY="${{ secrets.vps-ssh-key }}"
            echo VPS_SSH_KEY
            case "${{ inputs.service }}" in
              "${{ inputs.frontend-service-name }}") export FRONTEND_PORT=${{ inputs.port }} ;;
              "${{ inputs.backend-service-name }}") export BACKEND_PORT="${{ inputs.port }}" ;;
            esac

            docker compose pull ${{ inputs.service }}
            docker compose up -d --no-deps --force-recreate ${{ inputs.service }}
