name: Service deployment

on: 
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

      service:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.GH_PAT }}" | docker login ghcr.io \
              -u "${{ github.repository_owner }}" \
              --password-stdin

            cd projects/conduit-deployment

            export FRONTEND_PORT=${{ vars.FRONTEND_PORT }}
            echo "FRONTEND_PORT: $FRONTEND_PORT"
            export BACKEND_PORT=${{ vars.BACKEND_PORT }}
            export REPOSITORY_OWNER=${{ github.repository_owner }}
            export TAG=${{ inputs.tag }} 

            docker compose pull ${{ inputs.service }}
            docker compose up -d --no-deps --force-recreate ${{ inputs.service }}
